### ISSUE TITLE
tsify usage example needed

### ISSUE THREAD

**Issue by ducin** [TypeStrong/tsify#100]
Hello everybody,

I have a feeling that `tsify` will help me to use typescript compiling along with commonJS/browserify require function. But I couldn't find any example of tsify usage :( can somebody show a simple repository or even a gist, that would demonstrate the possibilities ot `tsify`?

----

I'm trying to come up with my own example, but I'm failing so far. I've got `greeter.ts` file:

```
class Greeter {
    greeting: string;
    constructor(message: string) {
        this.greeting = message;
    }
    greet() {
        return "Hello, " + this.greeting;
    }
}
```
and `app.ts` file:

```
///<reference path="greeter.ts" />

var greeter = new Greeter('everybody!');
console.log(greeter.greet());
```

when I run ` tsc --out app.js app.ts`, which is just simple typescript compiling on a single file that uses TS built-in references, I get app.js file that gets everything. 

----

And now the questions:

1. However, when I do `browserify app.ts -p [tsify] > bundle.js` (try to use browserify and tsify), I get the bundle.js file generated, but it's missing the greeter class - as if the reference was completely ignored. Why is that?

2. When I try to replace: `///<reference path="greeter.ts" />` with `require('./greeter');` and do the same command (`browserify app.ts -p [tsify] > bundle.js`) everything completely breaks and the bundle is empty. Is there any possibility to use commonJS require along with typescript compiling?

3. Can someone explain what precisely tsify brings me? I mean, what becomes unavailable if I quit using browserify? Is that using CommonJS's `require` function from TS level?

**Comment by smrq** [comment]
Congratulations!  You've opened the hundredth issue!   :100:  [Click here](https://github.com/TypeStrong/tsify/tree/master/examples/greeter) to claim your prize!  (Some restrictions apply.)

This was actually a great excuse to finally do some work for #68.  Hopefully the linked example will make things a little clearer.

**Comment by johnnyreilly** [comment]
Brilliant!

**Comment by smrq** [comment]
I added a simple JSX example as well.  Gonna call this done for now.

**Comment by basarat** [comment]
:rose: :heart:
