### ISSUE TITLE
Can tsify not include imports that resolve to `node_modules`?

### ISSUE THREAD

**Issue by ghpabs** [TypeStrong/tsify#102]
I don't need vendor files in my app bundle file.

**Comment by blakeembrey** [comment]
@ghpabs Can you provide an example or the error you're getting?

**Comment by ghpabs** [comment]
I wasn't getting any errors actually. The only problem was that all external modules were being bundled together into the output file.

In my setup I like to have - let's say for example - `libs.js` and `app.js` as separate files.

I'm now using `gulp-typescript`. The implementation can be found here: https://github.com/ghpabs/angular2-seed/

Cheers

**Comment by blakeembrey** [comment]
@ghpabs `tsify` might not be what you needed then. `tsify` is a plugin for Browserify, which is a CommonJS module bundler (it's designed to package everything into a single file for running on browsers) and includes vendor files by default. You can read about excluding modules in their documentation (https://github.com/substack/node-browserify#bexcludefile).

**Comment by ghpabs** [comment]
Thanks for clarifying the issue @blakeembrey. I'll def read more about `browserify`.
