### ISSUE TITLE
Problem installing - unmet peer dependency browserify@>= 6.x

### ISSUE THREAD

**Issue by spacejack** [TypeStrong/tsify#112]
Hopefully I'm not doing something stupid, but I'd like to install globally. I simply ran:

    npm install -g browserify

Then if I do:

    browserify --version

I get:

    13.0.0

Then I try

    npm install -g tsify

and get:

    tsify@0.13.2 requires a peer of browserify@>= 6.x but none was installed.

Not sure what to do.

**Comment by yangmillstheory** [comment]
I get the same.

Install browserify:

```shell
$ sudo npm install -g browserify
$ browserify --version
13.0.0
```

Install tsify:

```shell
$ sudo npm i -g tsify
/usr/local/lib
├── UNMET PEER DEPENDENCY browserify@>= 6.x
└─┬ tsify@0.13.2
  ├── convert-source-map@1.1.3
  ├── debuglog@1.0.1
  ├── lodash@3.10.1
  ├─┬ through2@2.0.0
  │ ├─┬ readable-stream@2.0.5
  │ │ ├── core-util-is@1.0.2
  │ │ ├── inherits@2.0.1
  │ │ ├── isarray@0.0.1
  │ │ ├── process-nextick-args@1.0.6
  │ │ ├── string_decoder@0.10.31
  │ │ └── util-deprecate@1.0.2
  │ └── xtend@4.0.1
  └── typescript@1.7.5

npm WARN EPEERINVALID tsify@0.13.2 requires a peer of browserify@>= 6.x but none was installed.
```

**Comment by spacejack** [comment]
@yangmillstheory I just posted this question on Microsoft/TypeScript gitter. Looks like tsify may not be necessary anymore(?)

> modules are a first class feature in TypeScript, so you should be able to use them without any external tools

> if you use moduleResolution=node and module=commonjs, it should work just fine
That's how I'm using TS with Browserify

**Comment by yangmillstheory** [comment]
@spacejack it's not necessary (you can compile to disk, then give browserify the entry point), but it's still useful for piping files straight into browserify.

**Comment by JAForbes** [comment]
@spacejack  I get the same error, but only if browserify is installed globally.

Try `npm install browserify tsify --save dev` and then 

`node_modules/.bin/browserify index.ts -p [ tsify --noImplicitAny ] > bundle.js` (as an example)

If that works then you can add the above script to your package.json scripts section

```
{
  "scripts": {
     "compile": "browserify index.ts -p [ tsify --noImplicitAny ] > bundle.js" 
  }
}
```

And then `npm run compile`,  hopefully that helps.  I'm just trying to get this working myself.
I think the module tsify is using to check dependencies is only checking the local dependencies.  But I could be mistaken.

**Comment by theoy** [comment]
@yangmillstheory wrote:
> it's not necessary (you can compile to disk, then give browserify the entry point), but it's still useful for piping files straight into browserify without doing intermediate I/O.

@yangmillstheory - do you know of a way to get `browserify` to recognise source maps on the .js files it consumes? When I tried raw `browserify` on *.js files generated by `tsc`, it didn't respect the matching *.js.map files that corresponded to the js files. My understanding was that `tsify` also gets that for its users, but I still have to try it out.

**Comment by smrq** [comment]
This is an issue with npm.  Bizarrely, when installing packages globally you have to specify all peerDependencies together in the same install command, or else you get that warning.

```
npm install -g browserify tsify
```

I don't think this is even an issue at runtime -- it should still work fine.  If you run `npm ls -g`, the warning shouldn't be there.

More discussion on a different package about this same issue: yeoman/generator-angular#1192

**Comment by bestori** [comment]
A quick workaround, for anyone tackling this (browserify 13.0.0, based on smrq's [link](https://github.com/yeoman/generator-angular/issues/1192) -

Simply install both dependencies over the same command.

i.e. 

npm install -g browserify browserify-incremental --save.

Hope this helps someone! :)
