### ISSUE TITLE
Mirror in-memory store to file system? (e.g. for tests)

### ISSUE THREAD

**Issue by theoy** [TypeStrong/tsify#114]
I noticed from the readme:
> **tsify** writes to an internal memory store before bundling, instead of to the filesystem.

Is there any advice for users that like to run tests off of unbundled ("loose") files? Right now, I'm using Browserify and TypeScript, but I'm running my tests as loose files under Node, and am importing the original source modules using Node resolution.

If I have loose files and loose source maps, both my test runner and debuggers like Webstorm are happy :smile:

Is there a way to get loose file mirroring with Tsify? (I love the fact that it bypasses IO for the sake of faster bundling).

**Comment by smrq** [comment]
This is an interesting request, but it's architecturally sort of problematic, and a bit of a niche use case anyway.  Honestly I'd recommend not using tsify in your case.  I could be wrong of course, but I doubt that bypassing IO makes enough of a difference to warrant the extra complexity in your build chain.

**Comment by theoy** [comment]
Cheers - thanks for the advice :smile:
