### ISSUE TITLE
Relative path to definitions file when project directory is a symlink

### ISSUE THREAD

**Issue by sta-ger** [TypeStrong/tsify#119]
Hi! My working directory is a symlink. When I'm trying to declare a relative path to definitions file

`/// <reference path="../../../../../typings/howlerjs/howler.d.ts" />`

I have an error

`Error TS2300: Duplicate identifier 'HowlerGlobal'`

But if I'll try to declare an absolute path to the source directory

`/// <reference path="c:/proj/typings/howlerjs/howler.d.ts" />`

everything works fine.

Is this an issue or I'm doing something wrong?

**Comment by cartant** [comment]
This is not directly related to `tsify`. It is a TypeScript problem, as it's a TypeScript error that you are receiving. Clearly, this is an old issue, but if still have problems of this nature, you might receive more assistance on [StackOverflow](http://stackoverflow.com/).
