### ISSUE TITLE
Compiling with jsx preserve results in an empty output (Typescript 1.8)

### ISSUE THREAD

**Issue by warhammerkid** [TypeStrong/tsify#128]
The `isTsx` method no longer exists, so `getCompiledFile` fails to find the compiled output if compiling with the `jsx` flag set to `preserve`. It appears to work if the `jsx` flag is set to `react`, because in that case the normalized filenames all end in `.js` instead of `.jsx`.

Replacing the line with the following seems to fix it:

    if (/\.tsx$/.test(tsFile)) {

**Comment by smrq** [comment]
This should have gotten fixed with 0.14.3.  Can you try it and verify?

**Comment by warhammerkid** [comment]
Once I get home I'll do some more digging, but it's definitely not working, although I suspect it's a different issue. I put a `console.log` in the constructor for Babelify, and it only sees the entrypoint when `preserve` is on, instead of all the files that imported. Furthermore, when the entrypoint file is a `.tsx` file, my output is empty (except for the browserify bootstrap code).

**Comment by warhammerkid** [comment]
In case it helps, with `preserve` on I get a cache miss that I don't get with `react`:

```
...
TSIFY 73816: 0.3111 sec -- createProgram
TSIFY 73816: 0.0003 sec -- syntax checking
TSIFY 73816: 0.9054 sec -- semantic checking
TSIFY 73816: 0.0737 sec -- emit program
TSIFY 73816: Compilation completed without errors
BABEL:  /Users/me/project/src/js/ENTRYPOINT.tsx { extensions: [ '.js', '.jsx', '.ts', '.tsx' ] }
BABEL:  /Users/me/project/src/js/ENTRYPOINT.tsx { sourceMaps: 'inline' }
TSIFY 73816: Cache miss on src/js/ENTRYPOINT.tsx
TSIFY 73816: New version of source file src/js/ENTRYPOINT.tsx (version undefined)
TSIFY 73816: Compiling files:
TSIFY 73816:   ./src/js/ENTRYPOINT.tsx
TSIFY 73816: 0.0128 sec -- createProgram
TSIFY 73816: 0 sec -- syntax checking
TSIFY 73816: 0.5133 sec -- semantic checking
TSIFY 73816: 0.0308 sec -- emit program
TSIFY 73816: Compilation completed without errors
```

**Comment by smrq** [comment]
Oh, I misunderstood the problem.  Yep, that makes sense... should be easy enough to fix.  Thanks for the log output, that illustrated the problem perfectly.

**Comment by smrq** [comment]
Ok, it seems that you have to add the `.tsx` extension to Babelify in order for it to operate on any files, even after they've been transpiled to jsx by tsify:

```sh
browserify -p [ tsify --jsx preserve ] -t [ babelify --presets [ react ] --extensions .tsx ] test/tsx/main.ts
```

There was also a fix on this end, which is out in tsify version 0.14.6.

Thanks for the report!
