### ISSUE TITLE
Cannot find module 'foo' (using gulp, browserify, tsify, babelify, typescript, ES6 modules)

### ISSUE THREAD

**Issue by GeorgeKnap** [TypeStrong/tsify#129]
Getting the `Cannot find module 'foo'` gulp task error when transpiling typescript files using tsify. Below is a sample of my gulp task and ts code. This is happening when importing Esri ArcGIS classes from d.ts module and using "new" keyword to create instance of the class. Note that using console `tsc` command **works without any error** and generates javascript files correctly.

## Gulp 
```
var gulp = require('gulp'),
    browserify = require('browserify'),
    vinylSource = require('vinyl-source-stream'),
    vinylBuffer = require('vinyl-buffer'),
    tsify = require('tsify'),
    tsc = require('typescript'),
    babelify = require('babelify'),
    es2015presets = require('babel-preset-es2015');

gulp.task('deploy-ts', function () {
const bundler = browserify({ basedir: 'app/', debug: true })
        .add('app.ts')
        .add('../typings/browser.d.ts')
        .plugin(tsify, { typescript: tsc })
        .transform(babelify.configure({ extensions: ['.ts', '.js'], presets: ['es2015'] }));

bundler.bundle()
        .pipe(vinylSource('app.min.js'))
        .pipe(vinylBuffer())
         ... some pipes for sourcemaps here...
        .pipe(gulp.dest('wwwroot/app'));
}
```
## tsconfig.json
```
"compilerOptions": {
    "noEmitOnError": true,
    "noImplicitAny": false,
    "removeComments": false,
    "sourceMap": true,
    "preserveConstEnums": true,
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node"
  }
```

## Typescript code sample
```
import {IArcGisMapService} from './arcgis-map.service'; //no problems importing and transpiling my own typescript code
import * as esri from 'esri';
import {Map} from 'esri/map';
import {Search} from 'esri/dijit/Search'; // esri import from d.ts file does not work when class is used

class EsriController {
    static $inject = ['$window', '$timeout', 'arcGisMapService'];

    private data: EsriMapViewModel;
    private map: Map;

    constructor(private $window: ng.IWindowService, private $timeout: ng.ITimeoutService, private arcGisMapService: IArcGisMapService) {
    }

    private $onInit = (): void => {

        this.arcGisMapService.getMap('gis-map').then((result: Map) => { //typechecking from d.ts. file without errors during transpilation
            this.map = result;

            let foo = new Search({}, ''); //error thrown when this line exists in code saying "Cannot find module 'esri/dijit/Search'"
        });

    };
}
```

I have tried more ways of using brwoserify. This one does TS -> ES6 -> ES5. I have also tried direct route to es5 without babelify. No luck. 

Any help appreciated!

**Comment by delphinus35** [comment]
```javascript
        .plugin(tsify, { typescript: tsc })
```

How about specifying `module` here?

```javascript
        .plugin(tsify, { typescript: tsc, module: 'es2015' })
```

And I think you should specify `module: "es2015"` instead of `"commonjs"` in `tsconfig.json`.

**Comment by GeorgeKnap** [comment]
Thanks for quick response. Still no change unfortunatelly.
```
Cannot find module 'esri/dijit/Search' 
```
I'm using Visual studio2015 and I don't get any error while coding. Only in gulp task.
also typescript version is latest 1.8.9 both in visual studio and installed globally.

**Comment by levibotelho** [comment]
I'm having a similar issue when running incremental builds, may or may not be related. Here's an extract from my build script.

```
var browserifyOptions = {
    debug: !shouldMinify(),
    entries: INDEX_JS_SOURCE,
    plugin: [tsify]
};

if (argv._.indexOf("dev") > -1) {
    browserifyOptions.cache = {};
    browserifyOptions.packageCache = {};
    browserifyOptions.plugin.push(watchify);
}

const browserifyInstance =
    browserify(browserifyOptions)
        .transform(stripBomify)
        .transform(preprocessify, getPreprocessOptions())
        .transform({global: true}, looseEnvify({_: "purge", NODE_ENV: shouldMinify() ? "production" : "development"}))
        .transform(babelify, {extensions: [".js", ".ts", ".tsx"], global: true})
        .transform(reactify);

gulp.task("client-javascript", ["eslint", "tslint"], function () {
    return browserifyInstance
        .bundle()
        .on("error", logError)
        .pipe(source("bundle.js"))
        .pipe(buffer())
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(gulpIf(shouldMinify(), uglify().on("error", gulpUtil.log)))
        .pipe(sourcemaps.write("./"))
        .pipe(gulp.dest(JS_CLIENT_BUILD_PATH));
});
```

When I run this script in watch mode (with the `dev` argument) it compiles correctly the first time around. However when I change a file and the incremental compilation kicks in I get a `Cannot find module` error and a slew of others afterwards due to the compiler not finding the module.

Another interesting note: My entry point contains `<reference>` statements. Before I didn't have these statements and instead included my `.d.ts` files as entry points and this would happen only occasionally, maybe on one incremental build out of four.

**Comment by cartant** [comment]
I've been going through some old, open issues and I found yours. This should be resolved by the `global` option that was added in 0.15.3:

    .plugin(tsify, { typescript: tsc, global: true })

Internally, `tsify` creates a transform and by default Browserify does not apply transforms to files from within `node_modules`.
