### ISSUE TITLE
Support custom locations for 'tsconfig.json'

### ISSUE THREAD

**Issue by DanielRosenwasser** [TypeStrong/tsify#132]
The fact that tsify tries to figure out the appropriate `tsconfig.json` is great, but some projects have several different `tsconfig.json` files (e.g. one for source alone, one for tests, etc.). @sandersn ran into this issue.

I would think there are two separate (but not mutually exclusive!) ways of going about this:

1. Keep the current behavior but respect Browserify's `basedir` setting when looking for a `tsconfig.json`.
2. Add an option to tsify itself to take a `project` or `tsconfigPath` option.

I think it would be a good idea to do both, but doing just one would go a long way.

**Comment by smrq** [comment]
Yep, both options make sense (and the latter was already suggested at #84).  I've just never gotten around to it.

PRs welcome, of course.  But I could probably knock this one out pretty quickly...

**Comment by smrq** [comment]
Okay, so as far as option 1 goes, I've made the change, but it won't work properly with TypeScript <1.9, since `ts.findConfigFile()` will prioritize a tsconfig in the CWD over whatever is passed in via `basedir`.  Works just fine with `typescript@next`.

**Comment by smrq** [comment]
Option 2, same caveat when configuring it with a directory.  Specifying a file works fine.  This will be out shortly.

**Comment by smrq** [comment]
Okay, try updating to v0.15.1.  This adds support for `--project`, which can be either a directory to search in (TS >= 1.9), or a tsconfig file, as well as the change to use `basedir` instead of the cwd when it is set.  (The `--project` setting takes precedence over `basedir`, which takes precedence over the cwd.)

**Comment by sandersn** [comment]
I tried 0.15.1 with `typescript` (not `typescript@next`). Explicitly specifying tsconfig's path works. Thanks!

**Comment by DanielRosenwasser** [comment]
Thanks a bunch @smrq!

**Comment by azarus** [comment]
So how do you define --project in tsify can't see a working example and --project is a command line argument, how am i supposed to use that in the gulp task?

**Comment by cartant** [comment]
@azarus tsify accepts compiler options specifed via the plugin options argument:

    browserify({
        entries: "index.ts"
    }).plugin("tsify", {
        project: "tsconfig.json"
    })

Also, if a project is not specified, tsify uses TypeScript's `findConfigFile` to locate one, so it's behaviour should be the same as tsc's if no project file is specified.

**Comment by azarus** [comment]
That doesn't seemed to work, anyways i went with a workaround requiring the json file.

**Comment by dbwodlf3** [comment]
also i am trying to apply this option. but it seems doesn't work..

**Comment by dbwodlf3** [comment]
yeah. it options doesn't work.

**Comment by dbwodlf3** [comment]
it works. but if you use complex build system.. then it can't works. but it's not problem of tsify..
almost you can resolve this problem with NODE_ENV flag.
just add extra path.. then maybe it will works.
