### ISSUE TITLE
Tsify doesn't work with symlinks

### ISSUE THREAD

**Issue by todddcls** [TypeStrong/tsify#135]
If you have a symlinked directory in your source tree, Tsify will fail to returned the compiled code to Browserify.  The problem is that Tsify stores files by their symlink path, and Browserify calls transform with the real path.

Possible options:
a) Create a secondary map in Host, that stores a path's real path, so that when transform is called, it can find it's original name.

b) Add an optional callback that can be used in transform to help map the file back.

**Comment by cartant** [comment]
This should be closed by #171.
