### ISSUE TITLE
Stopped compiling after update

### ISSUE THREAD

**Issue by alexk111** [TypeStrong/tsify#136]
Hi,

After updating *tsify* it stopped compiling. Prev version was **0.14.2**. I tested different versions, and it definitely appeared on **0.14.3**.
It seems that something wrong goes here: https://github.com/TypeStrong/tsify/blob/v0.15.2/lib/Tsifier.js#L273
When the ```normalized``` begins with ```../``` the resulting ```outputFile``` turns into ```__tsify__/../``` and it probably breaks the things.
If I remove the ```'__tsify__/' + ``` , everything starts working good.

In my environment the builder gulp is in a standalone folder:
```
- _builder
  - gulpfile.js
- build
- sources
  - app
    - app.ts
```
 that's why the normalized paths have the double-dots.

Hope this info will help.

Thanks.

**Comment by smrq** [comment]
Same as #137
