### ISSUE TITLE
compile file outside 'rootdir'

### ISSUE THREAD

**Issue by Halajohn** [TypeStrong/tsify#137]
A simple and reproducible example is as follows:

./a/browserify_script.js
./a/a.ts
/b.ts

the content of a.ts:
`import b = require("../b");
var a_var = b.b_var;`

the content of b.ts:
`export var b_var = 3;`

the content of browserify_script.js is (taken from the first example of tsify site)

    var browserify = require('browserify');
    var tsify = require('tsify');

    browserify()
        .add('a.ts')
        .plugin(tsify)
        .bundle()
        .on("error", function (error) {console.error(error.toString());})
        .pipe(process.stdout);

then execute this browserify_script.js from ./a/ folder.
The compilation result is ok, without any error, but if you look at the output - bundle.js, you will find the content of 'b.js' would be missing.

If you compile a.ts directly using tsc compiler under ./a/ folder, it actually complains about the following error message:

    D:\MyData\Temp\hhh\a>node ..\node_modules\typescript\bin\tsc --outDir __build__ --rootdir d:\MyData\Temp\hhh\a\  a.ts
    error TS6059: File 'D:/MyData/Temp/hhh/b.ts' is not under 'rootDir' 'd:\MyData\Temp\hhh\a\'. 'rootDir' is expected to contain all source files.

However, if you remove the '--rootdir' command line options, everything would be fine, it seems typescript compiler could automatically determine where the 'rootdir' is.

Hence, according to the latest tsify source codes, I comment out the following line in 'tsifier.js' file:

`// parsed.options.rootDir = currentDirectory;`

but the result is worse, even the content of a.js is missing, too.

It seems the file path finding logic in tsify conflicts the one in typescript compiler. The filename used in 'Tsifier.prototype.transform()' will be different from the one used in 'Host.prototype.writeFile()', and therefore the result is wrong.

**Comment by smrq** [comment]
Thanks for the report!  This should be fixed in v0.15.4.
