### ISSUE TITLE
Compiled files with random "path":undefined on Node 6 only

### ISSUE THREAD

**Issue by pocesar** [TypeStrong/tsify#138]
I'm not sure if it's node 6, or the 0.15.3 update, but I'm getting errors when generating code through the plugin

For example, in a few places, it's randomly showing things like this: 

```js
},{"./analytics":undefined,"./mask":undefined,"angular-errorlookup":1}],30:[function(require,module,exports){
/*..*/
},{"../../modules/analytics":undefined}],23:[function(require,module,exports){
/*..*/
},{"./cnpj":undefined}],46:[function(require,module,exports){
```

it was working before. I'll try to downgrade both node and tsify to see the culprit

EDIT: Ok, it's a problem with node 6. I've downgraded to Node 5.11 and it's working again. Now, I'm not sure if it's a problem with tsify, Typescript or Browserify! Sorry I can't help further

**Comment by mredbishop** [comment]
I have a host of broken code since upgrading to anything after node 6.

**Comment by basarat** [comment]
> node 6.

node 6 broke a bunch of my code as well. I'm sticking with node 5 :rose:
