### ISSUE TITLE
Different behaviour than tsc when tsconfig.json is present

### ISSUE THREAD

**Issue by martinleopold** [TypeStrong/tsify#147]
It seems that tsify will compile all .ts files it can find when a tsconfig.json file is present, even when an entry file is given.
This differs from `tsc` behaviour, which ignores the tsconfig.json when an input file is specified. (As outlined in [the docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html))

This is problematic since it results in compile time errors, when undesired files are compiled (even if they don't end up in the output). I got huge amounts of errors for example, because of .ts files from the node_modules folder being pulled in.

I have put a little test case together here: https://github.com/StudioProcess/tsify-test
There are a few npm scripts to run:

`npm run without-tsconfig`: desired behaviour. (only main.ts is compiled)
`npm run with-tsconfig`: error.ts is also pulled in, which results in an error.

Compare this to the `tsc` equivalents `npm run tsc-without-tsconfig` and `npm run tsc-with-tsconfig` which both run fine.

(The last script `npm run tsc-with-tsconfig-without-file` shows what tsc is doing when no input file is given. It compiles all .ts files and thus also results in an error.)

**Comment by cartant** [comment]
`tsc` doesn't ignore the entire `tsconfig.json`; it just overrides the `files` option.

tsify now (as at 3.0.4) lets you do something similar. You can override the `files`, `excludes`, and `includes` options. And, in particular, if `files` is specified as an empty array, only the Browserify entry points are used.
