### ISSUE TITLE
Usage of tsconfig.json field rootDir

### ISSUE THREAD

**Issue by DanielSchuech** [TypeStrong/tsify#148]
I think that the `rootDir` field of the tsconfig.json is currently not used by tsify.
A problem only exists when you use an es5 or es6 entry file for browserify and have no ts file in the same directory. The ts fiels will be recognized by tsify but are not cahced with the right folder structure so that they are not found by `getCompiledFile`.

The workaround is creating an empty ts file in the directory of the browserify entry file.

**Comment by cartant** [comment]
Could you give me an example of your hierarchy so that I can check this out? That is, this type of thing:

    project/
     ├── a.js
     └── b.ts

It's possible that this is fixed in #171. I'd like to make sure before I do the next release.

**Comment by DanielSchuech** [comment]
```
project/
 ├── subfolder
 │      └── b.ts
 └── entry.js
```

The `entry.ts` is the entry file for browserify. I load there `b.ts` with `require('./subfolder/b')`. In this case the file `b.ts`cannot be found. The problem is that tsify uses the folder in which the first ts file is found as root directory. Thats correct in the default way. There is an option `rootDir` in the tsconfig.json to change this behavior. This option has to be set to `project` in the example. I think that this option is currently not recognized by tsify.

I am currently working with the described workarround to create an empty ts file at the whished root. So my workarround folder sturcture looks like the following:
```
project/
 ├── subfolder
 │      └── b.ts
 ├── empty.ts
 └── entry.js
```

**Comment by cartant** [comment]
Thanks. I'll check it out.
