### ISSUE TITLE
Completely ignores nested imports starting with version 0.15.4

### ISSUE THREAD

**Issue by NeverwinterMoon** [TypeStrong/tsify#152]
The content of the imported file would look like this if the import is not done from the root file.
```
391:[function(require,module,exports){

},{}]
```

So, if c is imported from b and I run browserify + tsify on b, all is fine. If c is imported from b and b is imported from a and I run browserify + tsify on a, c will be empty.

**edit**: Yeah, I think this explains it better: https://github.com/TypeStrong/tsify/issues/148

The offending commit is this: https://github.com/TypeStrong/tsify/commit/a58508427354a60742a47628e88317786ab3518a

**Comment by cartant** [comment]
I've [asked for an example hierarchy](https://github.com/TypeStrong/tsify/issues/148#issuecomment-237994748) for the issue you've referenced. Could you provide me with one, too?

**Comment by cartant** [comment]
This should be closed by #174.
