### ISSUE TITLE
Move `typescript` as a dev dependency

### ISSUE THREAD

**Issue by basarat** [TypeStrong/tsify#153]
Its been raised before : https://github.com/TypeStrong/tsify/issues/85  Moving it to a dev dependency is what `ts-loader` does : https://github.com/TypeStrong/ts-loader/blob/master/package.json#L47 Mind if I do the same here. 

This will greatly help me in migrating babel/babelify projects to TypeScript. The projects I am migrating all use *only `npm`* scripts so I can't use the plugin api with `require('typescript')` to override the version :rose: 

/cc @smrq sorry for the hard direct mention :rose:

**Comment by blakeembrey** [comment]
Agreed @basarat 👍 We should work on making all the loaders BYOT (bring your own TypeScript) so people can upgrade independently.

**Comment by basarat** [comment]
Can I has npm access please 🐱

**Comment by blakeembrey** [comment]
Ah, I didn't see I had gotten access. Awesome 😄

**Comment by smrq** [comment]
Thanks for taking care of all this stuff guys!

**Comment by basarat** [comment]
Mind if I deploy this as `1.0.0`. Basically increment the major version as this is a breaking change as the users now need to `npm install typescript@whatever-version-they-want` as well :rose:
