### ISSUE TITLE
exclude @angular package

### ISSUE THREAD

**Issue by Dj-jom2x** [TypeStrong/tsify#165]
how to exclude @angular package ...

my exclude is 

```
  "exclude": [
   "node_modules",
   "vendor",
   "typings/index.d.ts"
 ]

but tsify also include @angular on the package and it makes the file 2mb 
```

**Comment by basarat** [comment]
> tsify also include @angular on the package 

I don't think its tsify. Its actually browserify. See https://github.com/TypeStrong/tsify/issues/160#issuecomment-232809531 for architecture notes. Basically we give `js` only for `ts` that browserify asks us, we don't push files *to* browserify, just compile the ones it asks us :rose:

**Comment by Dj-jom2x** [comment]
yeah sorry i go there and read abut exclude and it works but not all angular are excluded still 100kb xD

i done this by 
tsc angular2_app/main.ts --target ES5 --module system --experimentalDecorators --moduleResolution node --emitDecoratorMetadata --outFile scr/angular2_app/bundle_ts.js

then uglyfy ...

11 kb now
