### ISSUE TITLE
Output code even when there are compile errors

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/tsify#166]
If I compile a program using `tsc`, it will output JS even if there are compile errors. Is it possible to make tsify do the same? Or perhaps an option?

**Comment by cartant** [comment]
This issue has been raised before (#43 and #59). Reading #43, it seems that part of the problem with implementing this behaviour is that reporting non-fatal errors (i.e. warnings) to `browserify` is not possible. If you are using `gulp`, the author has suggested what seems to be [a workaround](https://github.com/TypeStrong/tsify/issues/43#issuecomment-101779946), but I've not tried it.

**Comment by OliverJAsh** [comment]
Thanks!
