### ISSUE TITLE
Error occurs when bundling tsx file.

### ISSUE THREAD

**Issue by rz-robsn** [TypeStrong/tsify#180]
Hi, 

tsify throws me an error when I try to compile a project that contains some JSX statements :

```
import {Observable} from 'rxjs/Rx';
import {run} from '@cycle/rxjs-run';
import {makeDOMDriver, h1, html} from '@cycle/dom';

function main() {
  const sinks = {
    DOM: Observable.interval(1000)
    .map(i =>
      <div>
          <input type="checkbox" /> Toggle me
          <p>ON</p>
      </div>
    )
  };
  return sinks;
}

const drivers = {
  DOM: makeDOMDriver('#app-container')
};

run(main, drivers);

```

and when I run the command 

`browserify app/renderer.tsx -p [ tsify -p app/ ] > /dev/null`

This error is shown 

```
Error: Parsing file /Users/rzrobsn/projects/tsify-bug/app/renderer.tsx: Unexpected token (8:22)
    at Deps.parseDeps (/Users/rzrobsn/projects/tsify-bug/node_modules/module-deps/index.js:453:28)
    at fromSource (/Users/rzrobsn/projects/tsify-bug/node_modules/module-deps/index.js:390:44)
    at /Users/rzrobsn/projects/tsify-bug/node_modules/module-deps/index.js:384:17
    at ConcatStream.<anonymous> (/Users/rzrobsn/projects/tsify-bug/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:185:7)
    at finishMaybe (/Users/rzrobsn/projects/tsify-bug/node_modules/concat-stream/node_modules/readable-stream/lib/_str
eam_writable.js:475:14)

    at endWritable (/Users/rzrobsn/projects/tsify-bug/node_modules/concat-stream/node_modules/readable-stream/lib/_str
eam_writable.js:485:3)
    at ConcatStream.Writable.end (/Users/rzrobsn/projects/tsify-bug/node_modules/concat-stream/node_modules/readable-s
tream/lib/_stream_writable.js:455:41)
    at DuplexWrapper.onend (/Users/rzrobsn/projects/tsify-bug/node_modules/readable-stream/lib/_stream_readable.js:507
:10)
```

The weird thing is that when I compile the code using the `tsc` compiles, everything runs fine.

You can find a minimal project for reproducing the issue [here](https://github.com/rz-robsn/tsify-bug), the npm scripts defined in this project contain the `tsc` command that works and the `browserify` command that does not.

Let me know if you need any more info and thanks !.

**Comment by cartant** [comment]
You will need to specify the `jsx` option (either in the `tsconfig.json` file or as a `tsify` option in the command line). If it's set to `preserve` rather than `react`, you will need some other Browserify transform following `tsify` - as Browserify will not parse JSX (that's the error you are seeing). There is a JSX example in this repo, if you need it.

**Comment by rz-robsn** [comment]
Hi @cartant, thanks for the quick response !

The minimal repo that I pointed to was actually slimmed version of another project I'm working on, so I didn't put information that I thought was not relevant there. In my current project I'm actually bundling my code this way :

```
browserify(files, {
    debug: true,
    cache: {},
    packageCache: {}
  })
  .plugin(tsify, { project : './app' })
  .transform(babelify, {
    presets:[
      'es2015'
    ],
    plugins:[
       "syntax-jsx",
       ["transform-react-jsx", {"pragma": "html"}]
    ],
    sourceMaps: "inline"
  }).bundle().pipe(fs.createWriteStream('out.js'));
```

As you can see, I'm using a babel plugin to convert my JSX statements into valid JS (the `jsx` option is set to `preserve` in my tsconfig). Yet still with this setup, I still have the same error.

I have updated the minimal project to include this code as well as my dependencies. You can see the error if you run `node browserify.js` 

Also, in case it's important, my node version is `v6.3.0` and my npm version is `3.10.3`.

Thanks

**Comment by cartant** [comment]
What you are attempting to do is pretty similar to an issue [I was helping someone with, a few days ago](https://github.com/TypeStrong/tsify/issues/175#issuecomment-238387030). The bit that's missing is the `extensions: ['.tsx']` option for `babelify`.

**Comment by rz-robsn** [comment]
That was it ! I missed the `extensions: ['.tsx']` part ! I should have looked at the babelify documentation more closely...

Thank you for your time and for this great plugin !

I'm closing this ticket since the solution was found.
