### ISSUE TITLE
Tsify output not included in build

### ISSUE THREAD

**Issue by krisdigital** [TypeStrong/tsify#182]
Trying to get a grunt build with tsify and babelify up and running. 

My Grunt Config:
```
browserify: {
      dev: {
        files: {
          'js/dist/app.js': ['js/*.js']
        },
        options: {
          configure: function(b) {
            b.plugin("tsify", { target: 'es6' }).transform("babelify", {presets: ["es2015"], extensions: ['.ts', '.js' ]});
          },
          browserifyOptions: {
            debug: true
          }
        },
      }
    },
```

The main file main.js

```
import hello from './modules/hello'
import TypeTest from './modules/type_test'

hello()
let typeTest = new TypeTest()

typeTest.test()
```

The modules/type_test.ts

```
class TypeTest {
  public test() {
    let str:string = "Test"
    console.log(str);
  }
}

export default TypeTest
```

resulting built app.js:
```
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
'use strict';

var _hello = require('./modules/hello');

var _hello2 = _interopRequireDefault(_hello);

var _type_test = require('./modules/type_test');

var _type_test2 = _interopRequireDefault(_type_test);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }


(0, _hello2.default)();


var typeTest = new _type_test2.default();

typeTest.test();

},{"./modules/hello":2,"./modules/type_test":3}],2:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = hello;
function hello() {
  console.log("Hello World!");
}

},{}],3:[function(require,module,exports){
"use strict";

},{}]},{},[1])
//# sourceMappingURL=app.map
```
The class/function from type_test is missing and `typeTest.test();` throws an error.

The export from the type_test.ts file is always empty. But the TypeScript file is compiled. If I compile TypeScript first, generating the according js files, and run browserify afterwards it works..

tsconfig.json
```
{
  "exclude": ["node_modules"],
  "compilerOptions": {
    "target": "es6",
    "allowSyntheticDefaultImports": true
  }
}
```

Any suggestions what could be the reason?

**Comment by cartant** [comment]
I can give this some more thought later, but my initial suggestion is to make the entry-point file a TS file. That is, rename `main.js` to `main.ts` and then use a single entry point in the Browserify configuration:

    files: {
      'js/dist/app.js': ['js/main.ts']
    }

Although, I usually use syntax like this (for `grunt-browserify`):

    browserify: {
        dev: {
            dest: "bundle.js",
            src: "index.ts"
        }
    }

But yours is likely correct, just unfamiliar, to me.

**Comment by krisdigital** [comment]
@cartant Thank you for your quick reply!  I just tried and it works so far, I can also import regular js with

```
    "allowJs": true
```

So that could be a solution!

Just wondering why the other way does not work.. Tried to debug it, but no clue why the compiled TS is not included..

**Comment by krisdigital** [comment]
Maybe you also have an idea why 

```
allowSyntheticDefaultImports: true
```

stops working after the change to .ts? I have to import like

```
import * as $ from jquery
```

to make it work..

Otherwise I get the error

> jquery_1.default is not a function

Sorry to bother you, having a hard time to get it running.. 🙄

**Comment by cartant** [comment]
I've not used `allowSyntheticDefaultImports`, so I can't really comment on that.

Regarding the initial problem, I suspect it has something to do with this part of the Babel configuration:

    extensions: ['.ts', '.js']

`tsify` also registers extensions. It does this by `unshift`-ing them onto the front of an array of extensions that Browserify uses when resolving modules/files. I suspect Babel does the same. Which means that there could be a `.js` extension infront of the `.ts` extension. That means Browserify will favour `.js` files over `.ts` files - which is not what `tsify` wants.

Unless you have a compelling reason for using Babel for the ES6 to ES5 transformation, you could make this bit simpler by targeting `es5` in `tsify` and removing Babel altogether. If you've included Babel in anticipation of using it for something like JSX transformation, you can still do that (others do), but in that case, you'd just look for `.tsx` and `.jsx` extensions.

**Comment by krisdigital** [comment]
@cartant Thank you for looking into it! I actually took out babelify and went full Typescript. There were also some inconsistencies with import statements between the two, so it is probably better that way. 
I started with a js file and wanted to throw in some Typescript here and there, but that was probably the thing that started the whole trouble!
Thank's again for your support!

**Comment by cartant** [comment]
No worries.
