### ISSUE TITLE
Prevent Tsify to read node_modules

### ISSUE THREAD

**Issue by GoldZeus** [TypeStrong/tsify#184]
Hello,
I'm trying to prevent tsify to read the node_modules directory as it has so many .ts files and they cause duplicate errors.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
 TypeScript error: admin/node_modules/bs-recipes/recipes/webpack.typescript.react/typings/browser/ambient/react-dom/index.d.ts(70,5): Error TS2300: Duplicate identifier 'export='.
```

How can I remove this directory? I tried adding an exclude to the tsify options but it doesn't help.
Thank you.

**Comment by cartant** [comment]
The options passed to `tsify` correspond to the `compilerOptions` in the `tsconfig.json` file. The `exclude` (and `file`) options are not compiler options, so they they'll be ignored, if passed to `tsify`.

To prevent `tsify` from reading the `node_modules` directory, you can:

* add an `exclude` option to `tsconfig.json` - e.g. `"exclude": ["node_modules"]`
* add a `file` option that is either empty or includes any `.d.ts` files you wish to use - e.g. `"files": ["./typings/index.d.ts"]`

Note that if `files` is specified, `exclude` is redundant.
