### ISSUE TITLE
TypeError: Cannot read property 'Preserve' of undefined

### ISSUE THREAD

**Issue by StanleyGoldman** [TypeStrong/tsify#185]
> var outputExtension = (self.opts.jsx === ts.JsxEmit.Preserve && isTsx(inputFile)) ? '.jsx' : '.js';
>                                                      ^
> TypeError: Cannot read property 'Preserve' of undefined
>     at Tsifier.getCompiledFile (\node_modules\tsify\lib\Tsifier.js:288:54)

**Comment by cartant** [comment]
Which `typescript` are you using? I don't see `JsxEmit` as `undefined` in any of 1.8.0, 2.0.0 or 2.1.0-dev.20160811.

**Comment by cartant** [comment]
I'm guessing it's 1.5. This situation makes a little more sense, now. (I've deleted a comment I placed against the PR - which I now think is okay.) Thanks.

**Comment by StanleyGoldman** [comment]
Hey @cartant,

I was in the process from upgrading from a really old version of tsify, and I didn't immediately realize what version of typescript I was using as a resut of the upgrade.

But you are right, I was using 1.5. I immediately switched to 1.8. So I dont know if this pull request is really valid.

**Comment by cartant** [comment]
No worries. I think it's still valid - now that I understand what's going on. And `tsify` doesn't - at this stage - specify a minimum version.
