### ISSUE TITLE
typescript dependencies

### ISSUE THREAD

**Issue by shibiaoz** [TypeStrong/tsify#193]
i install tsify,but run in error,Error: Cannot find module 'typescript'
```
gulp.task("default", ["copy-html"], function () {
    return browserify({
        basedir: '.',
        debug: true,
        entries: ['src/main.ts'],
        cache: {},
        packageCache: {}
    })
    .plugin(tsify)
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest("dist"));
});

so tsify dependcies should be 
"dependencies": {
    "convert-source-map": "^1.1.0",
    "fs.realpath": "^1.0.0",
    "through2": "^2.0.0",
    "tsconfig": "^2.2.0",
    "typescript": "~1.8.7"
  },
but not "typescript": "~1.8.7" in devDependencies
```

**Comment by cartant** [comment]
No, the behaviour you are seeing is the correct behaviour.

`typescript` is a [`peer dependency`](https://nodejs.org/en/blog/npm/peer-dependencies/) - as `tsify` supports a range of `typescript` versions. You will need to decide upon which version you wish to use and you will need to add it to the `package.json` of the project in which you are using `tsify`.

**Comment by cartant** [comment]
I will, however, update the installation instructions in the `README.md` so that this is clearer.

`typescript` was moved into `peerDependencies` in version 1.0.0 and the changelog includes some instructions, but it should be mentioned in the installation instructions, too. Thanks.
