### ISSUE TITLE
Detect fs case sensitivity based on it's real behavior

### ISSUE THREAD

**Issue by koroandr** [TypeStrong/tsify#200]
In lib/Host.js there is such line (134):

```js
    Host.prototype.useCaseSensitiveFileNames = function () {
		var platform = os.platform();
		return platform !== 'win32' && platform !== 'win64' && platform !== 'darwin';
	};
```

It detects case-sensitivity based on platform name, which is considered a [bad practice](https://nodejs.org/en/docs/guides/working-with-different-filesystems/).

I am working on Mac OS system with _case-sensitive_ file system, so the following code
```js
	Host.prototype.getCanonicalFileName = function (filename) {
		return ts.normalizeSlashes(ts.sys.useCaseSensitiveFileNames ? filename : filename.toLowerCase());
	};
```
breaks my paths.

I also created [similar issue](https://github.com/Microsoft/TypeScript/issues/11317) in TypeScript project.

**Comment by cartant** [comment]
That all sounds pretty reasonable. I'll look into it tomorrow. Thanks.

**Comment by koroandr** [comment]
I actually already did a quick fix for that - https://github.com/TypeStrong/tsify/pull/201
