### ISSUE TITLE
some @types definitions not loaded: node, core-js

### ISSUE THREAD

**Issue by DanielSchuech** [TypeStrong/tsify#203]
Hello,

Only the definitions of modules that are directly imported will be loaded.

The follwing works correctly with `tsc` and `browserify+tsify`:
 `npm i angular @types/angular`
```typescript
import * as ang from 'angular';
```

The follwing doesn't compile:
 `npm i angular @types/node`
```typescript
require('angular')
```
The compilation through `tsc` works without any error. But if i try to bundle it with `browserify+tsify` i get the error `Error TS2304: Cannot find name 'require'.`

My tsconfig.json:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "module": "commonjs",
    "target": "es5",
    "outDir": "dist"
  },
  "exclude": [
    "node_modules"
  ]
}
```

Compiled with `browserify index.ts -p [ tsify --noImplicitAny ] > bundle.js`

Typescript Version: 2.0.3
Tsify Version: 1.0.8

**Comment by cartant** [comment]
Thanks. I'll look into it.

**Comment by cartant** [comment]
If `typeRoots` and `types` are added to your `tsconfig.json`, it builds the bundle without error:

    {
      "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "noImplicitAny": true,
        "outDir": "dist",
        "sourceMap": true,
        "target": "es5",
        "typeRoots": ["node_modules/@types"],
        "types": ["core-js", "node"]
      },
      "exclude": [
        "node_modules"
      ]
    }

As to why this is required when using `tsify` and the TypeScript compiler API and not when using `tsc`, I'm not yet sure. I will have to look into it.

**Comment by cartant** [comment]
There is some information [here](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) on using `types` that suggests some caution might be required:

> If `types` is specified, only packages listed will be included.

However, if `types` is left out of the `tsconfig.json` that I listed above, the build fails.

I should have time to look more closely at this tomorrow.

**Comment by basarat** [comment]
> However, if types is left out of the tsconfig.json that I listed above, the build fails.

To use any globals you *must* include them somehow. Either through `tsconfig.json` (per project) Or using a reference directive (per file). So to use `node` (a global) `types` will be needed. 

I added a quick intro here as well : https://basarat.gitbooks.io/typescript/content/docs/types/@types.html :rose:

> i get the error Error TS2304: Cannot find name 'require'.

@DanielSchuech I doubt `tsc` is passing, it should give you the same error ^ . Check tsc version please :rose:

**Comment by cartant** [comment]
@basarat I've reproduced the OP's issue with TypeScript 2.0.3. `tsc` will build the project without error if neither `typeRoots` nor `types` is present in the `tsconfig.json`. And it also builds without error if only `typeRoots` is present.

The **`@types`, `typeRoots` and `types`** section of [this](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) page mentions the default inclusion of visible "@types" packages. Presumably, the described behaviour relates to `tsc`. Would you have expected the Compiler API to differ from this?

I've not yet spent much time looking into the issue. And I'm curious to hear your thoughts before I do so.

**Comment by basarat** [comment]
Hmm... I just did a quick test. `tsc` seems to work fine without `types` specified in tsconfig.json. My bad. Sorry ❤️

**Comment by blakeembrey** [comment]
Not sure if this is useful, but I believe I added `getDirectories` and `directoryExists` to the language services host to support this (if you haven't already - https://github.com/TypeStrong/ts-node/commit/240d4b9b751a5c551730a9856502f561844ae3b6).

**Comment by DanielSchuech** [comment]
If also seen some if conditions iff `getDirectories`and `directoryExists` exists. If this isn´t the case the was no lookup for the @types directory. I tried to replace them with fs functions in the Host file but that hasn`t resolved the problem.

Its a workaround to put all typings into the types array but I really like the idea to just add the required typings into the dependencies of the package.json. It would be one central point. Especially in big projects this would be interesting.

**Comment by cartant** [comment]
@blakeembrey Yep, that's done the trick. Thanks.

**Comment by basarat** [comment]
> I tried to replace them with fs functions in the Host file but that hasn`t resolved the problem.

Same for me. I added the following to alm but it didn't fix it for me :-/ 

![image](https://cloud.githubusercontent.com/assets/874898/19216377/aa9c6b64-8e04-11e6-99b3-8ca2c6b405e4.png)

**Comment by basarat** [comment]
Alright, looking at the TypeScript source code : https://github.com/Microsoft/TypeScript/blob/02493de5ccd9e8c4c901bb154ba584dee392bd14/src/compiler/moduleNameResolver.ts#L85 the `getCurrentDirectory` is the other magic function (in addition to `directoryExists`) that needs to be provided.

If I add that in, it works in alm (I have it hardcoded ... I will fill it up with the config file path ... this is just for demo + testing): 

![image](https://cloud.githubusercontent.com/assets/874898/19216430/53d20480-8e07-11e6-9ddf-724adae43d62.png)

The tip definitely saved me doing a lot of duplicate context expansion logic :rose:

**Comment by basarat** [comment]
### PS `getDirectories` :rose:

Seems required for completions : 

https://github.com/Microsoft/TypeScript/blob/94d895587ac20aa1bb11b67d7979fe6dbd8b86ca/src/services/types.ts#L165-L169

In addition to the other three functions required for completions: 

https://github.com/Microsoft/TypeScript/blob/94d895587ac20aa1bb11b67d7979fe6dbd8b86ca/src/services/types.ts#L143-L149

All four are definitely relevant for alm so I added it there, but YMMV :heart:

**Comment by cartant** [comment]
@basarat I had a look at the compiler host functions [listed here](https://github.com/Microsoft/TypeScript/blob/v2.0.3/src/compiler/program.ts#L978-L993) and added the following to tsify's host:

* `directoryExists`
* `getDirectories`
* `getEnvironmentVariable`
* `realpath`
* `trace`

tsify's host already had an implementation of `getCurrentDirectory`.

I'll add a commit after I've written some tests.

**Comment by cartant** [comment]
This should be closed by https://github.com/TypeStrong/tsify/commit/699c5fb48ebf9529675c10760db73f36b9e853e9

@basarat I added a test to check that tsify's `Host` implements the methods found in the host returned by TypeScript's `createCompilerHost`, so it ought to be pretty obvious if/when new methods need to be added to tsifiy's implementation.

**Comment by DanielSchuech** [comment]
Thanks for your work guys ;)
