### ISSUE TITLE
Accept project (-p) option as object

### ISSUE THREAD

**Issue by int0h** [TypeStrong/tsify#206]
As far as I understand I can pass some options to tsify like:
```javascript
.plugin(tsify, {
    optName: value
})
```
I can also provide "project" option:
```javascript
.plugin(tsify, {
    project: 'path/to/my/tsconfig.json'
})
```
But in my case I don't want to keep tsconfig.json (or I might like to generate it dynamically).
The only workaround I found so far is to stringify my config to json, write it to the disk, and pass the location of the file: 
```javascript
var config = {...};
var json = JSON.stringify(config);
fs.writeFileSync('some/temporary/place', json);

...

.plugin(tsify, {
     project: 'some/temporary/place'
})
```

That's definitely ugly! I wonder is it possible to pass an already parsed js-object as "project" option? Or maybe there is a better solution, I'd be glad if you suggest one.

Meanwhile I make kind of draft solution. You can find it here: https://github.com/int0h/tsify/commit/a4c7915214267d45843354d80fcc70777080d418

If that is acceptable I'll send pull request.

**Comment by cartant** [comment]
That sounds pretty reasonable to me. Send the PR.
