### ISSUE TITLE
Typings not found when using default typings path

### ISSUE THREAD

**Issue by bvblenny** [TypeStrong/tsify#208]
I am trying to migrate an Angular JavaScript (ES5) project to TypeScript 2.0 step by step and stumbled over a strange behaviour with tsify.
The build setup uses `gulp` with `browserify` and now also `tsify`.
I have a index.ts which `requires` some modules, so I used `npm install --save-dev @types/node`.

However the build fails with:

> TypeScript error: .tmp/public/app/index.ts(4,15): Error TS2304: Cannot find name 'require'.

Obviously it can't find the typings for node. After some debugging I noticed that it searches the _node_modules/@types_ folder in the root of my C: drive. Copying this folder to _C:\_ eliminates the error.

Explictly adding the **typesRoot** option in **tsconfig.json** fixed it. 
**tsconfig.json**

``` json
{
    "files": [
        "assets/app/index.ts"
    ],
    "compilerOptions": {
        "typeRoots" : ["./node_modules/@types"],
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false
    }
}
```

**browserify gulp task**

``` javascript
/** Bundles the application code and all its dependencies. */
    gulp.task('browserify-bundle', function () {
        var b = plugins.browserify({
            entries: '.tmp/public/app/index.ts',
            noBuiltins: true,
            insertGlobals: false,
            debug: true
            })
            .on('package', function (pkg) {
                dependencies.push(pkg);
            })
            .plugin(plugins.tsify, {
                target: 'es5'
            })
            .bundle()
            .pipe(plugins.sourceStream('app.js'))
            .pipe(plugins.buffer())
            .pipe(plugins.sourcemaps.init({
                loadMaps: true
            }))
            .pipe(plugins.sourcemaps.write('./'))
            .pipe(gulp.dest('.tmp/public'));
        return b;
    });
```

**Comment by cartant** [comment]
Thanks. I'll look into it.

**Comment by cartant** [comment]
I've finally gotten around to having a look at this and I'm unable to reproduce the error using files with paths similar to yours (`assets/app/index.ts` and `.tmp/public/app/index.ts`) and with the following versions:

    +-- @types/node@6.0.46
    +-- browserify@13.1.1
    +-- tsify@1.0.9
    `-- typescript@2.0.7

Are you sure you didn't have `"typeRoots": []` specified in your `tsconfig.json` file? That would disable the automatic inclusion of visible `@types`. If I specify an empty array, I see the error you mentioned.

**Comment by bvblenny** [comment]
Yes, I didn't have the `typeRoots` option in my `tsconfig.json`. If I remove from it the error appears when trying to build the app.

From my `package.json`:
```json
"@types/node": "^6.0.45",  
"browserify": "^11.2.0",  
"tsify": "^2.0.2",  
"typescript": "^2.0.3"
```

**Comment by ajmchambers** [comment]
I'm getting similar behaviour on my windows (10) machine (mac is fine): https://github.com/cyclejs-community/create-cycle-app/issues/41

(node `v6.9.0`, npm `v3.10.8`)

I've been able to reproduce the issue on two windows (10) machines using the following steps:

```bash
npm install -g create-cycle-app
create-cycle-app test-app-name
```

1. Select the `TypeScript + Browserify` option
2. Select the `XStream, tailored for Cycle.js` option

```bash
cd test-app-name
npm start
```

Eventually it will give the error:

```bash
TypeScript error: node_modules/@cycle/dom/lib/isolateModule.d.ts(6,35): Error TS2304: Cannot find name 'Map'.
```

---------------------------------------------

I've been doing my best with vscode's debugger trying to figure out whats happening.

So far this is what I've got:

```javascript
// Tsifier.js, line 91
var parsed = parseJsonConfigFileContent(
  config,
  ts.sys,
  configFile ? path.resolve(path.dirname(configFile)) : currentDirectory,
  null,
  configFile ? path.resolve(configFile) : undefined
);
```

The above for me ends up looking like:

```javascript
var parsed = parseJsonConfigFileContent(
  config,
  ts.sys,
  "c:\\Development\\test-typescript",
  null,
  "c:\\Development\\test-typescript\\tsconfig.json"
);
```

Then in the `parseJsonConfigFileContent` function in `typescript.js`:

```javascript
// typescript.js, line 46985
function parseJsonConfigFileContent(json, host, basePath, existingOptions, configFileName) {
    if (existingOptions === void 0) { existingOptions = {}; }
    var errors = [];
    var compilerOptions = convertCompilerOptionsFromJsonWorker(json["compilerOptions"], basePath, errors, configFileName);
    var options = ts.extend(existingOptions, compilerOptions);
    var typingOptions = convertTypingOptionsFromJsonWorker(json["typingOptions"], basePath, errors, configFileName);
    options.configFilePath = configFileName; // "c:\\Development\\test-typescript\\tsconfig.json"
    // ...
```

So `options.configFilePath` is set to: `"c:\\Development\\test-typescript\\tsconfig.json"`.

Then way later on:

```javascript
// typescript.js, line 44754
  function getEffectiveTypeRoots(options, host) {
      if (options.typeRoots) {
          return options.typeRoots;
      }
      var currentDirectory;
      if (options.configFilePath) {
          currentDirectory = ts.getDirectoryPath(options.configFilePath); // this bit here
      }
      else if (host.getCurrentDirectory) {
          currentDirectory = host.getCurrentDirectory();
      }
      return currentDirectory && getDefaultTypeRoots(currentDirectory, host);
  }
```

This part here:

```javascript
currentDirectory = ts.getDirectoryPath(options.configFilePath);
```

Will result with `currentDirectory` being `"c:"`.

For reference, on mac this value is being set to e.g.: `"/Users/ajmchambers/Documents/create-cycle-app/typescript-test"`

```javascript
// typescript.js, line 1830
function getDirectoryPath(path) {
    return path.substr(0, Math.max(getRootLength(path), path.lastIndexOf(ts.directorySeparator)));
}
```

Which looks like:

```javascript
getRootLength("c:\\Development\\test-typescript\\tsconfig.json") // 2
path.lastIndexOf("/") // -1
Math.max(2, -1) // 2
path.substr(0, 2) // "c:"
```

Thats as far as I've gotten, hopefully it helps track down whatever's going on.

**Comment by cartant** [comment]
@ajmchambers Thanks for the effort you've put into investigating this. The fact that the current directory ends up being `c:` suggests that there's a backslash replacement issue someplace. I'll look into this after I'm done with your PR.

**Comment by cartant** [comment]
@ajmchambers Could you do me a big favour and check to see whether or not the changes in [this branch](https://github.com/TypeStrong/tsify/tree/issue-208) address the issue?

**Comment by ajmchambers** [comment]
@cartant Just checked the branch and everything seems to be working nicely now, thanks.

**Comment by cartant** [comment]
@ajmchambers Thanks. Once it's confirmed that #212 is resolved (which it likely will be with your PR) I'll prepare a release.
