### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by maximilianschmitt** [TypeStrong/tsify#209]
Hi! I've seen a similar issue reported and discussed a couple of times but the suggested solutions don't quite seem to work for me.

```text
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
```

I'm using `node@5.9.1`, `tsify@2.0.2`, `typescript@2.0.6`, `browserify@13.1.1`.

I also put up a very small sample project to demonstrate the issue: https://github.com/maximilianschmitt/incremental-typescript-with-browserify

Here is a brief overview:

I'm starting my application at `src/main.js`. From there, I'm requiring a TypeScript file: `src/test.ts`. I'm using the following configurations to bundle this (note that I'm plugging in `tsify` before `babelify` as suggested in the [tsify README](https://github.com/TypeStrong/tsify#syntaxerror-import-and-export-may-appear-only-with-sourcetype-module)):

## Browserify 

```javascript
browserify('./src/main.js', { extensions: ['.ts'] })
  .plugin(tsify)
  .transform(babelify)
  .bundle()
  .pipe(process.stdout)
```

## Babel

```json
{
  "presets": ["es2015", "stage-2"]
}
```

## TypeScript

```json
{
  "compilerOptions": {
    "module": "es6",
    "target": "es6",
    "sourceMap": true
  }
}
```

Am I doing something wrong? I appreciate any help, thanks a lot! :)

**Comment by cartant** [comment]
The error you mentioned is the error that's thrown from Browserify if it receives an ES6 module.

Looking at your configuration, it seems it's likely that babelify is not transforming the modules output from tsify, as the `.ts` extension has not been included in babelify's options. Like this:

    browserify('./src/main.js')
      .plugin(tsify)
      .transform(babelify, { extensions: ['.ts'] })
      .bundle()
      .pipe(process.stdout)

Note that there is no need to include `extensions` in the Browserify options; tsify will handle ensure that it's included.

**Comment by maximilianschmitt** [comment]
Thanks for the fast reply @cartant. Unfortunately if I change the file to this, it doesn't make a difference, I still get the same error:

```javascript
'use strict'

const browserify = require('browserify')
const tsify = require('tsify')
const babelify = require('babelify')

browserify('./src/main.js')
  .plugin(tsify)
  .transform(babelify, { extensions: ['.ts'] })
  .bundle()
  .pipe(process.stdout)
```

```text
SyntaxError: import and export may appear only with sourceType: module
```

**Comment by cartant** [comment]
I've only just noticed that your entry file is a `.js` file. You will need to have `allowJs` set to `true` the `compilerOptions` in your `tsconfig.json` or in the options passed to `tsify`.

**Comment by maximilianschmitt** [comment]
I"m still getting the error unfortunately:

browserify.js:

```javascript
'use strict'

const browserify = require('browserify')
const tsify = require('tsify')
const babelify = require('babelify')

browserify('./src/main.js')
  .plugin(tsify)
  .transform(babelify, { allowJs: true, extensions: ['.ts'] })
  .bundle()
  .pipe(process.stdout)
```

tsconfig.json

```javascript
{
  "compilerOptions": {
    "allowJs": true,
    "module": "es6",
    "target": "es6",
    "sourceMap": true
  }
}
```

**Comment by cartant** [comment]
I would recommend your taking babelify out of the loop and changing the target to `es5`. If that works - as I'd expect it to - change it back to `es6`, put babelify back and look into your babel configuration. Is your `.babelrc` file in  the correct place and is it being used? Are your presets correctly installed? etc.

**Comment by maximilianschmitt** [comment]
Thanks @cartant. I got it running by setting `module` to `'commonjs'` in the tsconfig.json.
