### ISSUE TITLE
Why do we need tsify? Why not browserify the tsc compiled js?

### ISSUE THREAD

**Issue by ubershmekel** [TypeStrong/tsify#216]
I apologize if this is a silly question, but I've read the readme multiple times and googled yet could find no answer.

Why use tsify and not browserify the tsc output javascript files? Is it because of the map files?

**Comment by cartant** [comment]
I don't think it's a silly question. There's no reason that you *have* to use tsify and browserify. If you wanted to, yes, you could use tsc to output `js` files - which could then be bundled by browserify.

The reason I adopted tsify - I'm a maintainer, not the author - was that I had existing projects with well established, browserify-based build configurations. And adding a browserify plugin to perform the TypeScript transpilation was a much smaller change than re-configuring said projects to use tsc to output intermediate `js` files.

**Comment by ca0v** [comment]
Along those same lines, why not use tsc w/ --outFile and forgo browserify completely?  I'm not clear on what browserify give you beyond bundling.  I guess the answer is you need a system/amd shim when using tsc.

**Comment by nodefish** [comment]
Last time I checked, `outFile` was considered broken. It doesn't order the dependencies properly and can cause errors that are very hard to track. https://basarat.gitbooks.io/typescript/docs/tips/outFile.html
