### ISSUE TITLE
incorectly importing

### ISSUE THREAD

**Issue by mnewmedia** [TypeStrong/tsify#219]
Hi, sorry I am maybe wrong here but then you could point me to the right direction?

This is my gulp process
```js
gulp.task('ts',  function() {
    return browserify({debug: true})
        .add('./app/js/_main/main.ts')
        .plugin(tsify)
        .bundle()
        .on('error', function (e) {
            gutil.log(gutil.colors.red('Bundle error:', e.message));
        })
        .pipe(exorcist('./www/build/js/ts.js.map'))
        .pipe(source('ts.js'))
        //.pipe(buffer())
        //.pipe(uglify())
        .pipe(gulp.dest('./www/build/js/'));
});
```

Somewhere in my code I use the File Plugin from `ionic-native` like this:
```ts
import {FileEntry, File} from "ionic-native";
```

But in the output i guess it uses wrongly the `exports.FileReader()` but instead it should still be just `FileReader()`
```js
// original in File.ts
let reader = new FileReader();

// wrong output
 var reader = new exports.FileReader();
```

**Comment by cartant** [comment]
The import:

    import {FileEntry, File} from "ionic-native";

does not seem to mention `FileReader`.

**Comment by mnewmedia** [comment]
Mhm, I don't think I get what you are trying to tell me.
Yes `FileReader` is used in `File.ts` which gets importet and is a global var and should stay a global var.
But instead of leaving it a global it changes to `exports.FileReader`

**Comment by mnewmedia** [comment]
Oh wait I just found that in `node_modules` there is `dist/es5` and `dist/esm` in the `dist/es5` it is already like `exports.FileReader` so I must maybe find a way to get `File` from the `esm` folder...

**Comment by mnewmedia** [comment]
Seems to be an issue of ionic-native created issue there [#1188](https://github.com/driftyco/ionic-native/issues/1188).

Thanks anyway.
