### ISSUE TITLE
tsify does not properly synthesise default exports

### ISSUE THREAD

**Issue by sgen** [TypeStrong/tsify#223]
When browserifying typescript with `tsify` JQuery's synthetic default exports are not properly created, resulting in the following error: 

```
Uncaught TypeError: jquery_1.default is not a function
    at Object.2.jquery (index.js:10261)
    at s (index.js:1)
    at e (index.js:1)
    at index.js:1
```

Reproduction repository [here](https://github.com/sgen/tsify-issue-223-repro)

**Comment by cartant** [comment]
tsify does not generate code. It simply passes file contents to the TypeScript compiler, which generates the code, etc. What is generated will depend upon the `compilerOptions` that you have specified in your `tsconfig.json`. I would suggest using `tsc` to ensure that the `compilerOptions` you have specified generate the code that you are expecting. Then, once you are satisfied that the options are correct, go back to using tsify.

**Comment by sgen** [comment]
My mistake: I wasn't passing the `allowSyntheticDefaultImports` option to tsify directly:
`b.plugin('tsify', { allowSyntheticDefaultImports: true })`)
or my projects `tsconfi.json`:
`b.plugin('tsify', { project: './tsconfig.json' }
