### ISSUE TITLE
Error importing tsify into TypeScript gulpfile

### ISSUE THREAD

**Issue by kjiwa** [TypeStrong/tsify#224]
Hello. This is a question, not really an issue. Apologies if this is in an inappropriate forum--I'm pretty new to tsify and node.js (but not to JS).

I'm trying to create a gulpfile using TypeScript and I'm having trouble importing tsify. Here are my config files:

package.json:
```json
{
  "devDependencies": {
    "@types/browserify": "12.0.31",
    "@types/gulp": "4.0.4",
    "@types/vinyl-source-stream": "0.0.29",
    "browserify": "14.4.0",
    "gulp": "3.9.1",
    "gulp-typescript": "3.1.7",
    "ts-node": "3.0.6",
    "tsify": "3.0.1",
    "typescript": "2.3.4",
    "vinyl-source-stream": "1.1.0"
  }
}
```

gulpfile.ts:
```typescript
import * as browserify from 'browserify'
import * as gulp from 'gulp'
import * as source from 'vinyl-source-stream'
import * as ts from 'gulp-typescript'
import * as tsify from 'tsify'

gulp.task('default', function() {
  var args = {
    basedir: 'src/app',
    entries: ['app.component.ts']
  };

  return browserify(args)
    .plugin(tsify)
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest('dist'));
});
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "noImplicitAny": true
  }
}
```

When I try to build my project with "noImplicitAny" set to true, I get the following error:

```gulpfile.ts (5,24): Could not find a declaration file for module 'tsify'. 'node_modules/tsify/index.js' implicitly has an 'any' type. (7016)```

The error goes away and my build works correctly if I do either the following:

* set "noImplicitAny" to false
* use "var tsify = require('tsify')" instead of the import syntax

I would rather not do either of those, though. For other errors of this type, I've often been able to import some kind of a "@types" package, but I didn't notice one for tsify. Is there something else that I'm missing or doing incorrectly?

**Comment by cartant** [comment]
As a Browserify plugin, tsify has no API that you actually need to interact with, so providing TypeScript typings doesn't make a lot of sense. All of its interactions are with Browserify and options passed to Browserify.

Note that Browserify's `plugin` method can be passed a string. I would suggest not using an `import` or `require` at all; just pass `plugin` a string literal instead:

```ts
import * as browserify from 'browserify'
import * as gulp from 'gulp'
import * as source from 'vinyl-source-stream'
import * as ts from 'gulp-typescript'

gulp.task('default', function() {
  var args = {
    basedir: 'src/app',
    entries: ['app.component.ts']
  };

  return browserify(args)
    .plugin('tsify')
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest('dist'));
});
```

**Comment by kjiwa** [comment]
Ahh, good to know. The TypeScript web site uses "tsify" as a defined variable in their examples, so I assumed it needed to be listed as such: https://www.typescriptlang.org/docs/handbook/gulp.html.

Thank you for the feedback.

**Comment by cartant** [comment]
@kjiwa No worries.
