### ISSUE TITLE
All files are being type checked versus ones specified

### ISSUE THREAD

**Issue by JohnLouderback** [TypeStrong/tsify#226]
I have the following code:
```javascript
// Builds JS files for the specified cartridge
function jsBuild(cartridge) {
  var sitePath = './' + cartridge + '/cartridge/static/default/js/';
  var corePath = './core_commerce_richUI/cartridge/static/default/js/';
  tsconfig.rootDirs = [sitePath + 'src/', corePath + 'src/'];

  glob(sitePath + 'src/**.{js,ts}', function(err, files) {
    var tasks = files.map(function(entry) {
      console.log(entry);

      return browserify({
        debug: true,
        paths: [sitePath + 'src/', corePath + 'src/']
      }).add(entry)
        .plugin(tsify, tsconfig)
        .transform('babelify', {extensions: ['.ts', '.js']})
        .bundle()
        .on('error', function (error) { console.error(error.toString()); })
        .pipe(source(entry))
        .pipe(buffer())
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(uglify())
        .pipe(rename({
          extname: '.min.js',
          dirname: ''
        }))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(sitePath + 'built/'));
    });
  });
}
```

Without `tsify`, this build works perfectly fine. However, with it, I get errors from type checking on files that should not be type checked at all - for instance, our server-side JavaScript code. The server-side JavaScript code lives outside `sitePath + 'src/**.{js,ts}'` so it definitely should not be looked at by Typescript. What steps do I need to take to ensure that only the files in question are being type checked/compiled by Typescript?

**Comment by cartant** [comment]
Does the project have a `tsconfig.json` file?

**Comment by JohnLouderback** [comment]
Is there a way to disable to behavior of auto loading `tsconfig.json` then? I want to use this file for the purposes of the IDE, but I don't want the other behaviors. Any work around, if not?

**Comment by cartant** [comment]
No you cannot disable the loading of the `tsconfig.json`.

However, it's possible to tell tsify which config file it is to use, so create a `tsconfig-tsify.json` file and use `extends` to refer to your `tsconfig.json` file and override whichever settings you want to change:

```json
{
    "extends": "./tsconfig.json",
    "files": []
}
```

tsify's options include `project`, which can be used to tell it which config file you wish to use:

```ts
.plugin(tsify, { project: './tsconfig-tsify.json' })
```

**Comment by cartant** [comment]
Closing this, as I'm presuming the issue has been resolved.

**Comment by JohnLouderback** [comment]
Yes, that fixed it. Thank you for your help!
