### ISSUE TITLE
lazy loaded modules with angular 2

### ISSUE THREAD

**Issue by dmkit** [TypeStrong/tsify#231]
Hi,

Any tips on how to implement it with lazy loading modules with angular 2? Is there a way to compile all modules?

For example I'm getting: Cannot GET /app/profile/profile.module

**Comment by dmkit** [comment]
I moved to angular-cli instead. Thanks

**Comment by cartant** [comment]
No worries. Sorry for not getting back to you sooner; it was on my list of things to do today. The Angular CLI would be what I'd recommend, too. It's what I use, these days.
