### ISSUE TITLE
Add jsx flag in options?

### ISSUE THREAD

**Issue by epicfaace** [TypeStrong/tsify#232]
I get an error saying " Cannot use JSX unless the '--
jsx' flag is provided."

However, I am using tsify this way:
```
      b
      .plugin(tsify, { target: 'es6', jsx: true })
      .transform(babelify, {presets: ["react"], extensions: [ '.tsx', '.ts' ] })
      .bundle()
```

What am I doing wrong? How do I properly add the jsx flag here?

**Comment by cartant** [comment]
`true` is not a valid value for the `jsx` option. It can be either `"React"` or `"Preserve"` - see the documentation for TypeScript's [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html).
