### ISSUE TITLE
Type pollution caused by node modules

### ISSUE THREAD

**Issue by falsandtru** [TypeStrong/tsify#233]
I got the following error. This is caused by `@types/mocha`.

```
TypeScript error: node_modules/spica/throttle.ts(7,5): Error TS2322: Type 'Timer' is not assignable to type 'number'.
TypeScript error: node_modules/spica/throttle.ts(28,5): Error TS2322: Type 'Timer' is not assignable to type 'number'.
```

But I got no error with tsc command (`node_modules/.bin/tsc --noEmit -p tsconfig.json`). So this error seems to be caused by tsify.

repro:

1. Clone https://github.com/falsandtru/pjax-api
1. Run `npm i`
1. Run `npm i @types/mocha@2.2.45`
1. Run `gulp ts:test`

**Comment by cartant** [comment]
I see the error when running `tsc`:

```
C:\Users\Nicholas\Desktop\pjax-api>node_modules\.bin\tsc --noEmit -p tsconfig.json
node_modules/spica/throttle.ts(7,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
node_modules/spica/throttle.ts(28,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
```

**Comment by falsandtru** [comment]
I can repro, thanks. I'll move to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22510.
