### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by BobFrGit** [TypeStrong/tsify#234]
If I use browserify on my typescript generated JS files I get normal Unicode support

(I'm using VSCode on WIndows)

When I use 
```
browserify app.ts -p [ tsify ] > xbundle.j
```

I get 
```
    for (var σ£░µ¥┐ in theHouse.floors)
```
instead of

```
    for (var 地板 in theHouse.floors)
```

**Comment by cartant** [comment]
I'm unable to reproduce this. Would you be able to create a GitHub repository to reproduce the error?

**Comment by BobFrGit** [comment]
First, the solution is to use -o rather than > to generate the bundle.

Why am I using ">" -- the shorter answer is an accidental path to getting what seemed to work.

Turns out it's hard to repro because it depends on the particular shell and environment. It fails in VSCodes shell. There is more confusion because it depends on the file encoding so the file will "print" wrong in the windows shell (type) but may be fine in bash (cat).

The repro is very simple -- 

All I did was create app.ts
```
var 地板 = "Hello";
console.log(`Hello ${地板}`);
```
and then

```
browserify app.ts -p [ tsify ] > bundle.js
```
it helps to erase the bundle.js first to get a fresh encoding -- sometimes it's UTF8 and other times UTB16LE. And when reading the file I find that if my editor (Epsilon -- an Emacs for Windows) sees the buffer exists it will use the old encoding so I have to delete the buffer first.

**Comment by cartant** [comment]
With verified UTF8 source files (both `.js` and `.ts`) that contain:

```
var 地板 = "Hello";
console.log(`Hello ${地板}`);
```

I am unable to reproduce the problem on Windows using any of the following:

* a Git Bash shell;
* a CMD.EXE shell;
* VS Code's terminal.

The input files and the effected bundles (written as new files) all contain the UTF8 sequences:

```
E5 9C B0 E6 9D BF
```

**Comment by BobFrGit** [comment]
Given that -o works fine I won't worry about it.

**Comment by BobFrGit** [comment]
Just an FYI -- found https://github.com/browserify/browserify/issues/349 which addressed the same issue and came to the same -o conclusion. It seems powershell related.

**Comment by cartant** [comment]
Thanks.
