### ISSUE TITLE
Cannot use typescript class from other local typescript module

### ISSUE THREAD

**Issue by Sheldan** [TypeStrong/tsify#235]
I have a common npm module containing TypeScript which is an node module providing some classes and functionality. This module is packaged via `browserify` + `tsify` (a plugin for compiling typescript) and also exports the declaration files and built with `gulp`.

I have another npm module using TypeScript which imports this module locally via `file:../modulename` and tries to use functionality from the first module. The second module is also packaged via `browserify` + `tsify` and built with `gulp`. The compilation of the second module works via `npx tsc`, but fails if I execute the gulp build file with the error message

> Error: Cannot find module './AbstractClass' from 'folderInOtherModuleContainingTheJSFiles'

Interestingly it sometimes fails with this Class sometimes with another, so it seems there is also some kind of concurrent processing.

I extracted the failing code from my project and created a minimal example with this behavior [here](https://github.com/Sheldan/npm-minimal-working-example).

**Comment by cartant** [comment]
Have you determined whether or not it's possible do build your `including-module` using `tsc`? That is, using the TypeScript command-line compiler?

I always encourage devs to test the behaviour with `tsc` if they encounter problems. If `tsc` cannot do something, tsify won't be able to, either. And if the same error is effected, then it's not a tsify problem.

**Comment by Sheldan** [comment]
If I compile them via `npx tsc` it works.

**Comment by cartant** [comment]
Does it work if the common module is built using tsify/Browserify and the including module is built using `tsc`?

And are you making sure the common module is reinstalled into the including module with each rebuild? My understanding - and experience - is that dependencies using `file` only copy the specified directory into `node_modules` upon the first install.

**Comment by Sheldan** [comment]
Both modules modules are built using `tsify`/`browserify`, I built the common module without `browserify` before, but it didnt work, so I changed it for safe measures. 
The including module only works if built via `tsc` and not via the gulp file using `browserify`/`tsify`.
As far I can see the reference to the common module is done via a symlink by npm, which should cause it to be up to date forever.

**Comment by cartant** [comment]
Hmm, is npm's use of a symlink for `file` dependencies something that's changed in version 5? It always used to be a simple - i.e. next-to-useless - copy operation. I abandoned npm for yarn sometime ago and I've not used 5.

Could you provide some version information for Node and npm. And what platform are you building on?

**Comment by Sheldan** [comment]
I read that there is a `npm link` comand, but this way is an alternative to that and the solution should work.

npx: `9.7.1`
node: `v9.5.0`
npm: `5.6.0`

Fedora 27 with 4.15.7 Kernel 64 Bit

**Comment by cartant** [comment]
I'll have a look at it soon. Thanks for preparing the minimal example, by the way. It's certainly appreciated.

**Comment by Sheldan** [comment]
Thanks, I was trying to track down the issue and figured using only the bare bones would help me/others in that.

**Comment by cartant** [comment]
I've found the problem and it's not a problem with tsify. If you look in the bundle created for `common-module2`, you'll find this bit of code:

```js
},{}],3:[function(require,module,exports){
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./AbstractClass"));
__export(require("./ClassWhichHasNothingToDoWithIt"));
```

When Browserify consumes that bundle, it attempts to resolve the `require` calls therein. And that is the problem. If the `require` parameter is renamed, the problem goes away:

```js
},{}],3:[function(r,module,exports){
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(r("./AbstractClass"));
__export(r("./ClassWhichHasNothingToDoWithIt"));
```

I would suggest that you fix the problem by uglifying the bundle that's created for `common-module2`.

**Comment by Sheldan** [comment]
Thats a very weird issue. Parts of the solution were based of the typescript documentation, do you think there should be an issue there? Or where does the require come from?

**Comment by cartant** [comment]
I can't say the the problem surprises me. It has nothing to do with TypeScript.

The problem is with Browserify re-bundling a bundle that it has generated. The search it has for `require` calls is not sufficiently sophisticated to determine that what is a `require` parameter is not a call to Node's `require`. That's all.

I doubt Browserify was written with the expectation that it would be consuming its own bundles.

**Comment by Sheldan** [comment]
It can still happen if I reference a library which was bundled using browserify, in which case I can only use it via uglifying or renaming the method. Which I somewhat consider a bug on browserify's side, but thats not for me to decide.

As it was not a problem with tsify itself and is working for me now, this issue can be closed. Thanks :)
