### ISSUE TITLE
Syntax errors crash watchify

### ISSUE THREAD

**Issue by itsoli** [TypeStrong/tsify#24]
Following gulp task crashes on errors raised by the tsc.

``` javascript
var gulp = require('gulp');
var gutil = require('gulp-util');
var source = require('vinyl-source-stream');
var watchify = require('watchify');
var livereload = require('gulp-livereload');
var browserify = require('browserify');
var xtend = require('xtend');

gulp.task('bundle', function () {
  var args = xtend({debug: true}, watchify.args);
  var b = watchify(browserify(args)
    .plugin('tsify', {
      target: 'ES5',
      module: 'AMD',
      noImplicitAny: true
    }));

  b.on('update', bundle);
  b.add('./app/scripts/app.ts');

  function bundle() {
    return b.bundle()
      .on('error', function (e) {
        gutil.log(gutil.colors.red('Bundle error:', e.message));
      })
      .pipe(source('bundle.js'))
      .pipe(gulp.dest('build'))
      .pipe(livereload());
  }
  return bundle();
});
```

I've tested the task w/o the tsify plugin/plain js and it works as expected.

**Comment by aciccarello** [comment]
> OK, figured out what was wrong with my test. In short: it was calling `.on('error', ...)` before `bundle()` instead of after, which means it was watching the Browserify instance instead of the pipeline, so it successfully caught the errors when it shouldn't have.

Ah, this helped me realize an issue in my gulp build. I'm not sure if I missed this because I don't understand streams well but I feel like this should be documented somewhere.

Is this something that is true for all watchify builds?

**Comment by smrq** [comment]
Yep
