### ISSUE TITLE
Doesn't work with es2018

### ISSUE THREAD

**Issue by falsandtru** [TypeStrong/tsify#241]
With https://github.com/falsandtru/spica, tsify returns unexpected token error as follows.

```
$ node_modules/.bin/browserify src/cofetch.ts -p [ tsify -t esnext ] > /dev/null
SyntaxError: Unexpected token (13:20) while parsing ...\spica\src\cofetch.ts while parsing file: ...\spica\src\cofetch.ts
```

Or browserify's problem?

**Comment by cartant** [comment]
I would imagine it's the latter.

**Comment by falsandtru** [comment]
I see, I'll open an issue on browserify.

**Comment by cartant** [comment]
I'd suggest running `tsc` on it and attempting to Browserify its output files.

**Comment by falsandtru** [comment]
Yep, see https://github.com/browserify/browserify/issues/1843#issuecomment-396773231

**Comment by falsandtru** [comment]
Fixed on upstream, thanks.
