### ISSUE TITLE
Dont wrap bundle inside anonymous function

### ISSUE THREAD

**Issue by Acidic9** [TypeStrong/tsify#247]
I'm trying to bundle some TypeScript code into one single file, and after coming across tsify, it looked perfect but unfortunately tsify wraps the bundle inside an anonymous function causing exposed functions in the main entry file to be inside it's own scope.

For example:

```ts
// main.ts
class MyClass {
}
```

Will be transformed into this:

```ts
// bundle.js
(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
class MyClass {
}
},{}]},{},[1]);
```

And in my particular use case, I really need `MyClass` to not be wrapped inside anything.
Is there an option for this or anything I can do to get passed this?

**Comment by cartant** [comment]
This is how Browserify works. Tsify is a Browserify plugin and there's nothing that can be done about this.

**Comment by Acidic9** [comment]
I thought so, thanks for such a quick reply. I was able to solve it in this case by just assigning `MyClass` to window.

**Comment by cartant** [comment]
For a more 'official' way of doing it, have a look at https://stackoverflow.com/a/41518610/6680611

**Comment by Acidic9** [comment]
Thank you, thats exactly what I needed
