### ISSUE TITLE
Cannot find module with @types import

### ISSUE THREAD

**Issue by Acidic9** [TypeStrong/tsify#248]
I am unable to import a module from a TypeScript @types package.
In my main file I have:
```ts
import { BdApi } from 'bandaged__bdapi'
console.log(BdApi)
```
This compiles correctly when I run `tsc` but not with `node build.js`.

My tsconfig looks like this:
```json
"compilerOptions": {
	"target": "es6",
	"module": "es6",
	"moduleResolution": "node"
}
```

And my build.js file:
```js
const browserify = require('browserify');
const tsify = require('tsify');
const babelify = require('babelify');

browserify()
	.add('src/main.ts')
	.plugin(tsify)
	.transform(babelify, { extensions: ['.ts', '.tsx'] })
	.bundle()
	.on('error', function (error) { console.error(error.toString()); })
	.pipe(process.stdout);
```

And my .babelrc
```json
{
	"presets": ["@babel/preset-env"]
}
```

And the output when running `node build.js`
```
Error: Cannot find module 'bandagedbd__bdapi' from 'C:\Users\...\src'
```

I can `import * as React from 'react'` from `@types/react`, but not `import { BdApi } from 'bandagedbd__bdapi'`.

**Comment by cartant** [comment]
This is not a tsify problem. That package has no available `@types`:

```
$ npm dist-tag ls @types/bandaged__bdapi
npm ERR! dist-tag ls Couldn't get dist-tag data for @types/bandaged__bdapi
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/-/package/@types%2fbandaged__bdapi/dist-tags

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicholas\AppData\Roaming\npm-cache\_logs\2019-01-10T12_12_53_795Z-debug.log
```

**Comment by Acidic9** [comment]
@cartant Sorry, that's a handwritten typo - It should be `bandagedbd__bdapi`. In my TypeScript file it is correct, just in that code snippet I did a typo.

**Comment by cartant** [comment]
You should first verify that the import works with a plain vanilla `.ts` file that's compiled using `tsc`.

**Comment by Acidic9** [comment]
![Imgur](https://i.imgur.com/936a0dk.png)

yep, unfortunately still doesn't work.
