### ISSUE TITLE
Importing nodejs types pollutes global types

### ISSUE THREAD

**Issue by falsandtru** [TypeStrong/tsify#267]
You are importing browserify, and browserify imports nodejs: https://github.com/TypeStrong/tsify/blob/6b7a4f1a94ebd891bd8b4d53d1e82deb0a767edc/index.d.ts#L1

This makes type errors https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22510. Can you remove that import?

**Comment by cartant** [comment]
Removed in 5.0.2.

**Comment by falsandtru** [comment]
thx
