### ISSUE TITLE
Examples!

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/tsify#68]
It would be great to have some Hello World style examples of how TSIFY could be used.  Generally I find that's a fantastic resource for any project to have.

For myself I'd really like to see an example of how to use TSIFY in concert with React.  Despite my best efforts I've tried and failed (despite getting really close) to get TSIFY and React playing nice together.  Unfortunately deadlines means I've had to abandon it again for now but I'd love to come back to this.

Pretty please! :tulip: :gift: :gift_heart:

**Comment by smrq** [comment]
Sure, that's a great idea.  Docs are good!

**Comment by smrq** [comment]
I've added tsify versions of the basic Greeter and JSX examples.  Gonna call this done for now.
