### ISSUE TITLE
Karma and reference files

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/tsify#77]
Hey,

I'm converting over some tests to use TSIFY and the only way I can introduce the typings appears to be using the old school reference syntax in each file to bring in the jasmine typings:

```
/// <reference path="../../typings/jasmine/jasmine.d.ts" />
```

Is there another way to achieve this? I've tried playing with `tsconfig.json` and the `files` prop of the `karma.conf.js` to no avail...

**Comment by dpogue** [comment]
My experience is that this worked with tsconfig.json as of tsify@0.11.11, but appears to have broken in tsify@0.11.12.
Can you try tsify 0.11.11 and see if it resolves the issue for you?

**Comment by smrq** [comment]
I did make an error in 0.11.12 (which I'm presently trying to write a test for to prevent regressions) -- sorry about that!  Hopefully 0.11.13 fixes that.  If not, I would be interested to know whether 0.11.11 does work.  The `files` prop of `karma.conf.js` *should* work fine.

**Comment by johnnyreilly** [comment]
Hi @smrq,

I just upgraded to 0.11.15 and the files prop doesn't work I'm afraid.  I tried this but to no avail:

```
    files: [
      'test/**/*.tests.ts', 'typings/jasmine/jasmine.d.ts'
    ],
```

:sob:

**Comment by dpogue** [comment]
`files` isn't allowed to use wildcards for some bizarre reason. It must list each .ts file individually (if you're using Atom as your editor, you can use wildcard in `filesGlob` and it will generate the `files` array for you). `excludes` (in TypeScript 1.6) has the same restriction :(

@smrq 0.11.15 did fix the issue I was seeing about reference files.

**Comment by johnnyreilly** [comment]
Hi @dpogue,

You're talking about `tsconfig.json`, I'm talking about `karma.conf.js` :smile: 

For clarify the files portion of my `tsconfig.json` looks like this: 

```
    "files": [
        "index.tests.ts",
        "../../typings/jasmine/jasmine.d.ts"
    ]
```

and the files portion of my `karma.conf.js` looks like this: (globs are allowed in karma.conf.js to my knowledge)

```
    files: [
      'test/**/*.tests.ts', 'typings/jasmine/jasmine.d.ts'
    ],
```

But I still have an issue with reference files...

So for you it's working just with the tsconfig.json change?

**Comment by dpogue** [comment]
Ahh, our karma.conf.js has `files: ['src/**/*.ts']`, but we have a test_helper.ts file that uses a `///<reference>` which is imported by all of our tests.

**Comment by johnnyreilly** [comment]
Ah - I might try that!

**Comment by smrq** [comment]
Closing old issues; I think most(?) of these issues should be resolved with the recent updates to tsconfig handling.
