### ISSUE TITLE
Move to TypeStrong organisation

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/tsify#80]
Hi @smrq!

We're working on bring together the various TypeScript compiler options and would love to have `tsify` join @TypeStrong. This would ensure improved support, help the community standardise on implementations and make this the "go to" implementation.

**Comment by johnnyreilly** [comment]
Not that I have a vote but :+1: from me!

**Comment by smrq** [comment]
Sure, sounds good to me :+1:

**Comment by blakeembrey** [comment]
@smrq Awesome, thanks! I just sent you an invitation and you'll be able to move it across :smile:

**Comment by jbrantly** [comment]
Cool! I like this general move to TypeStrong.
