### ISSUE TITLE
tsconfig option

### ISSUE THREAD

**Issue by basarat** [TypeStrong/tsify#84]
tsify uses ts.findConfigFile from current directory : https://github.com/TypeStrong/tsify/blob/f8105a64236892e5401641214772319e7e8a3384/lib/Tsifier.js#L38 so you need to provide the path yourself. It needs to have an option `tsconfig` to allow the user to provide an explicit path to tsconfig. 

refs https://github.com/TypeStrong/meta/issues/1
/cc @johnnyreilly

**Comment by smrq** [comment]
Fixed (about time, huh?) in v0.15.1.
