### ISSUE TITLE
tsify should use `typescript` as a `peerDependency`

### ISSUE THREAD

**Issue by basarat** [TypeStrong/tsify#85]
Otherwise the user installed version isn't used 
Code : https://github.com/TypeStrong/tsify/blob/f8105a64236892e5401641214772319e7e8a3384/package.json#L31

/cc @johnnyreilly

**Comment by johnnyreilly** [comment]
Given the [changes to peerDependencies in npm 3](https://github.com/npm/npm/issues/6565) should this be a devDependency instead?

**Comment by nycdotnet** [comment]
Whatever the solution is for this should probably be the solution for grunt-ts too bearing npm 3 in mind.

I'm still annoyed they're doing this.

**Comment by blakeembrey** [comment]
> should this be a devDependency instead?

I don't think using `devDependency` would work for what you want, except in development here. Personally, I prefer the `peerDependency` changes - it was too easy to get into a broken state with npm before. Not saying this is the best solution, but personally, it is better. I've just opted to tell people to install what they want themselves and you could put TypeScript as a peer dependency for that (but I'd probably use `*` to avoid anyone running into issues installing).

**Comment by smrq** [comment]
I'm not really convinced that this is the correct course of action.  There's lots of arguments for both sides happening across a lot of different threads in various repos, but ultimately the way I'm reading the comments from the npm team, `dependency` is the correct type for TypeScript.

https://github.com/npm/npm/issues/6565#issuecomment-76482462

In this case, "I need this thing directly available to me" applies to the TS compiler, whereas "if you want to use me, *you* need this thing available to *you*" applies to Browserify.

I'm open to further discussion, though.

Note that you can pass in whatever compiler you like with the `typescript` API option (the name of which I'm definitely open to changing per TypeStrong/meta#1).

**Comment by blakeembrey** [comment]
@smrq The issue is with `dependency` you can't actually pass a custom compiler using `--typescript` as you are using `require` - which would resolve to your own instance before the users instance. The only way to solve that and keep it as a dependency would be to resolve the users `typescript` instance starting two directories up.

**Comment by smrq** [comment]
@blakeembrey Well, I guess that's true if you're using the CLI.  With the API it would work as I stated:

https://github.com/TypeStrong/tsify/blob/f8105a64236892e5401641214772319e7e8a3384/index.js#L7-L8

As long as the caller passes `require('typescript')` and not just `'typescript'`, the module will be resolved relative to the caller, which is what you'd expect.

**Comment by basarat** [comment]
You can leave it as it is, but I've added docs so that its clear that if they want to use their version they need to specify it : https://github.com/TypeStrong/tsify/pull/87 :rose:  Close this if you are okay with that :+1:

**Comment by smrq** [comment]
Thanks for the docs update.  I'll keep things as is for now but I'm keeping an eye on TypeStrong/meta#1 and other discussion.  I'm hoping that as npm 3 adoption settles down, a single dominant pattern gets established across the community.

**Comment by basarat** [comment]
> I'm hoping that as npm 3 adoption settles down, a single dominant pattern gets established across the community.

Just info that might already be common knowledge: There is no pattern for dev tools ... but for front-end libs `peerDependency` is still the way to go. One does not want people installing two version of `react` or `jquery` or `insert famous lib here` :rose:
