### ISSUE TITLE
Error TS2307: Cannot find module 'module-name'.

### ISSUE THREAD

**Issue by bennylut** [TypeStrong/tsify#89]
attempting to use tsify cause the error: Error TS2307: Cannot find module 'module-name'. 
while when using tsc (the typescript compiler) no error is produced. 

here is a simplified setup to reproduce the problem:

# tsconfig:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": true,
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true,
        "outDir": "target/",
        "moduleResolution": "node",
        "sourceMap": true
    },
    "filesGlob": [
        "**/*.ts",
        "**/*.tsx",
        "!node_modules/**"
    ],
    "files": [
        "src/app.ts",
    ],
    "exclude": []
}
```

# app.ts:
```
import io = require('socket.io-client');
```

# gulpfile:
```
var browserify = require('browserify');
var tsify = require('tsify');
var source = require('vinyl-source-stream');

function compileClientJs() {
  var bundler = browserify({
      debug: true
    })
    .add('src/app.ts')
    .plugin('tsify');

  return bundler.bundle()
    .on('error', function (error) { console.error(error.toString()); })
    .pipe(source('app.js'))
    .pipe(gulp.dest('dist'));
}

gulp.task('build', compileClientJs);
```

Assume that all required packages are installed using npm.
The exact error given this setup will be: 

`TypeScript error: src/app.ts(1,21): Error TS2307: Cannot find module 'socket.io-client'.`

simply calling 'tsc' on the commandline works without producing any errors.

**Comment by smrq** [comment]
Try adding `.add('path/to/your/typings.d.ts')` to your gulpfile.  tsify
does not look at the `files` or `filesGlob` properties of your tsconfig,
and that sometimes means you miss some .d.ts files.  This is behavior I'm
probably planning to change in the future -- I believe that ts-loader does
respect those fields for *.d.ts, and I'd like more feature parity between
the two.

**Comment by bennylut** [comment]
Thanks, that solved that immediately.. 
For others benefit I will post the gulpfile with the fix, note that this gulpfile assumes that the `typings` directory contains all your `d.ts` files. 

# gulpfile:
```
var browserify = require('browserify');
var tsify = require('tsify');
var source = require('vinyl-source-stream');
var walkSync = require('walk-sync');

function compileClientJs() {
var bundler = browserify({
      debug: true
    }).add('src/app.ts');

   walkSync('typings').forEach(function(file) {
    if (file.match(/\.d\.ts$/)) {
      bundler.add("typings/" + file);
    }
  });
  bundler.plugin('tsify');

  return bundler.bundle()
    .on('error', function (error) { console.error(error.toString()); })
    .pipe(source('app.js'))
    .pipe(gulp.dest('dist'));
}
gulp.task('build', compileClientJs);
```

**Comment by jbrantly** [comment]
FWIW, ts-loader does respect `files` (but not currently `filesGlob`). All it does is additionally load those files into the language service/program (but it doesn't limit the application to *just* those files).
