### ISSUE TITLE
Grunt & Browserify: 'import' and 'export' may appear only with 'sourceType: module' (2:0)

### ISSUE THREAD

**Issue by davidreher** [TypeStrong/tsify#92]
Hey, 

I know I have to run babelify after tsify is run, but I cannot figure out how to do so.

My browserify configuration looks like this:
```
module.exports = function () {
  return {
    options: {
      plugin: [['tsify', {target: 'es6'}]],
      transform: ['babelify', ['envify', {NODE_ENV: 'production'}]],
      extensions: ['.js', '.jsx', '.ts', '.tsx']
    },
    build: {
      options: {
        browserifyOptions: {
          debug: true
        }
      },
      src: ['<%= paths.APP_JS %>'],
      dest: '<%= paths.DEBUG_BUNDLE %>'
    }
  }
};
```
Any ideas?

**Comment by logashoff** [comment]
Are you sure you need to target es6? I had the same issue, but I've changed target to es5. By default it targets es3.

**Comment by davidreher** [comment]
actually I want to run it through babel to get some more features, such as automatic 'use strict', and removing additional , at the end of objects ...
when not targeting ES6 I do not get any errors, because the typescript output is just working with browserify ... but then the ```import``` statements are not working ...

**Comment by smrq** [comment]
Cleaning up old issues; this should now be documented in the README
