### ISSUE TITLE
Error TS2307: Cannot find module

### ISSUE THREAD

**Issue by JonathanMEdwards** [TypeStrong/tsify#93]
I see a bunch of other reports of this error but I still don't understand how to fix it. Further, this error only occurs for me in a freshly cloned directory, not in my main development directory. Based on reading the other issues I suspect the problem is tsify ignoring something in tsconfig.json but I have no clue what to do to fix it. Can we get some guidance on this issue?

**Comment by JonathanMEdwards** [comment]
For others encountering this problem here was my solution. There was a .d.ts file for one of my modules listed in the files: section of tsconfig.json. I added it as an input file to the browserify command.

**Comment by smrq** [comment]
Cool, sounds like you got it sorted.  Supporting tsconfig's `files` property is next on my todo list (#94).
