### ISSUE TITLE
Fails with TypeScript 1.7

### ISSUE THREAD

**Issue by dpogue** [TypeStrong/tsify#99]
Error message is `ts.parseConfigFile is not a function`.

There are no listed compiler API changes on the TypeScript wiki for 1.7.x though :(

**Comment by blakeembrey** [comment]
Sadly the API changed in 1.7 (there's a few other breaking things I've hit already too). Here's the difference: https://github.com/TypeStrong/ts-node/blob/master/src/ts-node.ts#L27-L39 (implementor note: I don't recommend the custom interfaces).

**Comment by smrq** [comment]
Thanks @blakeembrey, that'll save me some time.

All my tests pass after changing that bit, so hopefully that's all that this will take.

**Comment by smrq** [comment]
This specific thing is fixed in 0.13.0.  Try it and see if everything else is good.

**Comment by dpogue** [comment]
Yep, 0.13.0 looks good. Thanks!
